### ISSUE TITLE
Scroll position persists when navigating to a new page

### ISSUE THREAD

**Issue by DoDung-BePresent** [Hoang-Nguyen-Huy/fer-lab1#26]
@Hoang-Nguyen-Huy When navigating to a new page by clicking an item at the bottom of the current page, the new page opens with the scroll position at the bottom, instead of resetting to the top.

Test case 1:
- Go to bottom of page
- Click item!
![Screenshot 2024-11-16 202359](https://github.com/user-attachments/assets/13af0218-abb6-40fa-9240-1e48ae918e8c)
- Move to new page with position at bottom of page
![image](https://github.com/user-attachments/assets/f848368b-4c43-4cba-b750-b8be570786c2)
- Desired position should be at the top of the page.
![image](https://github.com/user-attachments/assets/af9d7220-3134-47f6-87b9-e0c6f7b5c8d5)
**Solution**:
- Use useEffect hook in detail page!
```
useEffect(() => {
  window.scrollTo(0, 0);
}, []);
```

**Comment by Hoang-Nguyen-Huy** [comment]
thank you very much for opening this issue <3
